import React, { useState } from 'react';
import * as Icons from 'lucide-react';
import { Search } from 'lucide-react';

const ALL_ICONS = [
  // Educational / Academic
  'BookOpen',
  'Book',
  'BookMarked',
  'BookCopy',
  'GraduationCap',
  'School',
  'Calculator',
  'Microscope',
  'FlaskConical',
  'Atom',
  'Globe',
  'Map',
  'Compass',
  'Ruler',
  'PenTool',
  'Sigma',
  'Pi',
  'Variable',
  'Infinity',
  'BarChart',
  'BarChart2',
  'LineChart',
  'PieChart',
  'Library',
  'Newspaper',
  // Writing / Office
  'Pencil',
  'Pen',
  'Edit',
  'Edit2',
  'Edit3',
  'FileText',
  'File',
  'Files',
  'Clipboard',
  'ClipboardType',
  'Notebook',
  'NotebookPen',
  'NotebookTabs',
  'Type',
  'AlignLeft',
  'AlignCenter',
  'AlignRight',
  'AlignJustify',
  'Highlighter',
  'Underline',
  'Bold',
  'Italic',
  'Strikethrough',
  'Quote',
  'Paperclip',
  // Communication
  'Megaphone',
  'Bell',
  'BellRing',
  'BellDot',
  'MessageCircle',
  'MessageSquare',
  'Messages',
  'Mail',
  'MailOpen',
  'Phone',
  'PhoneCall',
  'Volume',
  'Volume1',
  'Volume2',
  'VolumeX',
  'Mic',
  'MicOff',
  'Speaker',
  'Radio',
  'Rss',
  'Broadcast',
  // People
  'User',
  'Users',
  'UserCheck',
  'UserPlus',
  'UserCircle',
  'UserSquare',
  'Baby',
  'PersonStanding',
  'Contact',
  'HeartHandshake',
  'Handshake',
  'UsersRound',
  'UserRound',
  'CircleUser',
  // Time / Calendar
  'Clock',
  'Clock1',
  'Clock2',
  'Clock3',
  'Clock4',
  'Clock5',
  'Clock6',
  'Clock7',
  'Clock8',
  'Clock9',
  'Clock10',
  'Clock11',
  'Clock12',
  'Timer',
  'TimerOff',
  'TimerReset',
  'AlarmClock',
  'AlarmClockCheck',
  'AlarmClockOff',
  'Calendar',
  'CalendarDays',
  'CalendarClock',
  'CalendarCheck',
  'CalendarCheck2',
  'CalendarX',
  'CalendarX2',
  'CalendarPlus',
  'CalendarRange',
  'Hourglass',
  'Watch',
  'Sunrise',
  'Sunset',
  // Status / Alerts
  'Check',
  'CheckCircle',
  'CheckCircle2',
  'CheckSquare',
  'X',
  'XCircle',
  'XSquare',
  'AlertCircle',
  'AlertTriangle',
  'AlertOctagon',
  'Info',
  'HelpCircle',
  'ShieldAlert',
  'ShieldCheck',
  'CircleAlert',
  'OctagonAlert',
  'TriangleAlert',
  // Emotions / Reactions
  'Star',
  'StarOff',
  'StarHalf',
  'Heart',
  'HeartOff',
  'HeartCrack',
  'ThumbsUp',
  'ThumbsDown',
  'Smile',
  'SmilePlus',
  'Frown',
  'Meh',
  'Laugh',
  'Angry',
  'PartyPopper',
  'Sparkles',
  'Flame',
  'Zap',
  'ZapOff',
  'Siren',
  // Actions / Controls
  'Plus',
  'PlusCircle',
  'Minus',
  'MinusCircle',
  'ArrowRight',
  'ArrowLeft',
  'ArrowUp',
  'ArrowDown',
  'ArrowUpDown',
  'ArrowLeftRight',
  'ChevronRight',
  'ChevronLeft',
  'ChevronUp',
  'ChevronDown',
  'ChevronsRight',
  'ChevronsLeft',
  'ChevronsUp',
  'ChevronsDown',
  'Undo',
  'Undo2',
  'Redo',
  'Redo2',
  'RefreshCw',
  'RefreshCcw',
  'RotateCcw',
  'RotateCw',
  'Play',
  'PlayCircle',
  'Pause',
  'PauseCircle',
  'StopCircle',
  'SkipForward',
  'SkipBack',
  'Repeat',
  'Repeat1',
  'Shuffle',
  'FastForward',
  'Rewind',
  // Organization / Layout
  'LayoutGrid',
  'LayoutDashboard',
  'LayoutList',
  'LayoutTemplate',
  'LayoutPanelLeft',
  'LayoutPanelTop',
  'Grid2x2',
  'Grid3x3',
  'ListTodo',
  'List',
  'ListChecks',
  'ListOrdered',
  'ListPlus',
  'Layers',
  'Layers2',
  'Layers3',
  'Folder',
  'FolderOpen',
  'FolderPlus',
  'FolderCheck',
  'FolderTree',
  'Tag',
  'Tags',
  'Bookmark',
  'BookmarkCheck',
  'BookmarkPlus',
  'ClipboardList',
  'ClipboardCheck',
  'ClipboardCopy',
  'Archive',
  'ArchiveRestore',
  'Inbox',
  'InboxIcon',
  'Table',
  'Table2',
  'TableProperties',
  // Objects / Items
  'Trophy',
  'Award',
  'Medal',
  'Flag',
  'FlagTriangleRight',
  'Target',
  'Crosshair',
  'Rocket',
  'Lightbulb',
  'LightbulbOff',
  'Key',
  'KeyRound',
  'KeySquare',
  'Lock',
  'LockOpen',
  'Unlock',
  'Shield',
  'ShieldHalf',
  'Puzzle',
  'Dice1',
  'Dice2',
  'Dice3',
  'Dice4',
  'Dice5',
  'Dice6',
  'Gamepad',
  'Gamepad2',
  'Joystick',
  'Swords',
  'CircleDot',
  'Dices',
  // Technology
  'Monitor',
  'MonitorSmartphone',
  'Tablet',
  'Smartphone',
  'SmartphoneCharging',
  'Laptop',
  'Laptop2',
  'Keyboard',
  'Mouse',
  'Printer',
  'Settings',
  'Settings2',
  'Sliders',
  'SlidersHorizontal',
  'SlidersVertical',
  'ToggleLeft',
  'ToggleRight',
  'Wifi',
  'WifiOff',
  'Battery',
  'BatteryCharging',
  'BatteryFull',
  'Cpu',
  'CircuitBoard',
  'HardDrive',
  'Database',
  'Server',
  'Bot',
  'Code',
  'Code2',
  'Terminal',
  'QrCode',
  // Media
  'Music',
  'Music2',
  'Music3',
  'Music4',
  'Video',
  'VideoOff',
  'Camera',
  'CameraOff',
  'Image',
  'ImageOff',
  'ImagePlus',
  'Film',
  'Clapperboard',
  'Headphones',
  'HeadphoneOff',
  'Tv',
  'Tv2',
  'Projector',
  'Podcast',
  'PlaySquare',
  // Nature
  'Sun',
  'SunMoon',
  'SunDim',
  'Moon',
  'MoonStar',
  'Cloud',
  'CloudSun',
  'CloudRain',
  'CloudSnow',
  'CloudLightning',
  'CloudFog',
  'Snowflake',
  'Wind',
  'Tornado',
  'Leaf',
  'Leaves',
  'TreeDeciduous',
  'TreePine',
  'Flower',
  'Flower2',
  'Sprout',
  'Cactus',
  'Mountain',
  'MountainSnow',
  'Waves',
  'Thermometer',
  'Rainbow',
  'Droplets',
  'Droplet',
  // Animals
  'Fish',
  'Snail',
  'Bug',
  'Bird',
  'Dog',
  'Cat',
  'Rabbit',
  'Turtle',
  'Squirrel',
  'Rat',
  'Egg',
  'PawPrint',
  'Feather',
  // Food / Drink
  'Apple',
  'Banana',
  'Cherry',
  'Grape',
  'Citrus',
  'Coffee',
  'CoffeeIcon',
  'Tea',
  'Pizza',
  'Sandwich',
  'Utensils',
  'UtensilsCrossed',
  'Cookie',
  'Candy',
  'Cake',
  'Croissant',
  'Soup',
  'Salad',
  'IceCream',
  'IceCream2',
  'Beef',
  'Carrot',
  'Popcorn',
  // Health / Body
  'Activity',
  'HeartPulse',
  'Dumbbell',
  'Brain',
  'Eye',
  'EyeOff',
  'Ear',
  'EarOff',
  'Hand',
  'HandMetal',
  'Accessibility',
  'Stethoscope',
  'Pill',
  'Hospital',
  'Syringe',
  'Bandage',
  // Art / Design
  'Palette',
  'PaintBucket',
  'Paintbrush',
  'Paintbrush2',
  'Eraser',
  'Scissors',
  'Crop',
  'Frame',
  'Aperture',
  'Brush',
  'Wand',
  'Wand2',
  'PenLine',
  'Spline',
  // Places / Transport
  'Home',
  'House',
  'Building',
  'Building2',
  'Store',
  'Warehouse',
  'Landmark',
  'Castle',
  'Church',
  'Plane',
  'PlaneTakeoff',
  'PlaneLanding',
  'Car',
  'Bus',
  'Train',
  'Bike',
  'Ship',
  'Anchor',
  'Navigation',
  'Navigation2',
  'MapPin',
  'MapPinned',
  'Globe2',
  'Tent',
  'Fence',
  // Misc / Fun
  'Crown',
  'Diamond',
  'Gem',
  'DollarSign',
  'Coins',
  'CreditCard',
  'Banknote',
  'Receipt',
  'Box',
  'Package',
  'Package2',
  'PackageOpen',
  'Gift',
  'GiftIcon',
  'Send',
  'SendHorizontal',
  'Share',
  'Share2',
  'Link',
  'Link2',
  'ExternalLink',
  'Download',
  'Upload',
  'Search',
  'SearchCode',
  'Filter',
  'SortAsc',
  'SortDesc',
  'Hash',
  'Percent',
  'MoreHorizontal',
  'MoreVertical',
  'Grip',
  'GripHorizontal',
  'GripVertical',
  'Sparkle',
  'CirclePlus',
  'CircleMinus',
  'Shapes',
  'Pentagon',
  'Hexagon',
  'Octagon',
  'Triangle',
  'Square',
  'Circle',
];

// Deduplicate and keep only names that resolve to a real lucide-react component
const VALID_ICONS = Array.from(new Set(ALL_ICONS)).filter(
  (name) => name in (Icons as Record<string, unknown>)
);

interface IconPickerProps {
  value: string;
  onChange: (val: string) => void;
}

export const IconPicker: React.FC<IconPickerProps> = ({ value, onChange }) => {
  const [search, setSearch] = useState('');

  const filteredIcons = search.trim()
    ? VALID_ICONS.filter((name) =>
        name.toLowerCase().includes(search.toLowerCase())
      )
    : VALID_ICONS;

  return (
    <div className="space-y-2">
      <label className="block text-xs font-bold uppercase text-slate-500">
        Icon (Lucide Name or URL)
      </label>
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full border border-slate-300 rounded px-2 py-1 text-sm"
        placeholder="e.g. Zap or https://..."
      />
      <div className="relative">
        <Search
          size={13}
          className="absolute left-2 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none"
        />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full border border-slate-200 rounded pl-7 pr-3 py-1 text-xs bg-slate-50 focus:outline-none focus:border-indigo-300"
          placeholder={`Search ${VALID_ICONS.length}+ icons…`}
        />
      </div>
      <div className="flex flex-wrap gap-1 p-2 bg-slate-50 rounded border border-slate-200 max-h-44 overflow-y-auto">
        {filteredIcons.map((name) => {
          const Icon = (Icons as unknown as Record<string, React.ElementType>)[
            name
          ];
          if (!Icon) return null;
          return (
            <button
              key={name}
              type="button"
              onClick={() => onChange(name)}
              className={`p-1.5 rounded hover:bg-slate-200 transition-colors ${
                value === name ? 'bg-indigo-100 text-indigo-600' : ''
              }`}
              title={name}
              aria-label={`Select ${name} icon`}
            >
              <Icon size={16} />
            </button>
          );
        })}
        {filteredIcons.length === 0 && (
          <p className="text-xs text-slate-400 py-2 px-1">
            No icons found. Enter the name in the field above.
          </p>
        )}
      </div>
    </div>
  );
};
