sed -i 's/text-\[10px\]/text-xxs/g' components/common/DriveDisconnectBanner.tsx
sed -i 's/text-\[9px\]/text-xxxs/g' components/common/DriveDisconnectBanner.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/admin/TalkingToolConfigurationPanel.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/admin/NextUpConfigurationPanel.tsx
sed -i 's/text-\[11px\]/text-xxs/g' components/admin/CalendarConfigurationModal.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/admin/CalendarConfigurationModal.tsx
sed -i 's/text-\[9px\]/text-xxxs/g' components/admin/CalendarConfigurationModal.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/admin/ScheduleConfigurationPanel.tsx
sed -i 's/text-\[11px\]/text-xxs/g' components/widgets/MathToolWidget.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/widgets/MathToolWidget.tsx
sed -i 's/text-\[9px\]/text-xxxs/g' components/widgets/MathToolWidget.tsx
sed -i 's/text-\[10px\]/text-xxs/g' components/widgets/Schedule/Settings.tsx
sed -i 's/text-\[11px\]/text-xxs/g' components/widgets/CalendarWidget.tsx
