export const BLOOMS_DATA = {
  keyWords: [
    {
      level: 'Level 1: Recall/Knowledge/Memory',
      words: [
        'Recognize',
        'List',
        'Describe',
        'Retrieve',
        'Name',
        'Find',
        'Match',
        'Recall',
        'Select',
        'Label',
        'Define',
      ],
    },
    {
      level: 'Level 2: Understanding/Comprehension',
      words: [
        'Compare',
        'Contrast',
        'Demonstrate',
        'Describe',
        'Interpret',
        'Explain',
        'Extend',
        'Illustrate',
        'Infer',
        'Outline',
        'Relate',
        'Rephrase',
        'Translate',
        'Summarize',
        'Show',
        'Classify',
      ],
    },
    {
      level: 'Level 3: Application',
      words: [
        'Apply',
        'Build',
        'Choose',
        'Construct',
        'Demonstrate',
        'Develop',
        'Draw',
        'Experiment with',
        'Illustrate',
        'Interview',
        'Make use of',
        'Model',
        'Organize',
        'Plan',
        'Select',
        'Solve',
        'Utilize',
      ],
    },
    {
      level: 'Level 4: Analysis',
      words: [
        'Analyze',
        'Categorize',
        'Classify',
        'Compare',
        'Contrast',
        'Discover',
        'Divide',
        'Examine',
        'Group',
        'Inspect',
        'Sequence',
        'Simplify',
        'Make distinctions',
        'Relationships',
        'Function',
        'Assume',
        'Conclusions',
      ],
    },
    {
      level: 'Level 5: Synthesis or Create',
      words: [
        'Design',
        'Construct',
        'Produce',
        'Invent',
        'Combine',
        'Compile',
        'Develop',
        'Formulate',
        'Imagine',
        'Modify',
        'Change',
        'Improve',
        'Elaborate',
        'Plan',
        'Propose',
        'Solve',
      ],
    },
    {
      level: 'Level 6: Evaluation',
      words: [
        'Awared', // As in PDF
        'Choose',
        'Defend',
        'Determine',
        'Evaluate',
        'Judge',
        'Justify',
        'Measure',
        'Compare',
        'Mark',
        'Rate',
        'Recommend',
        'Select',
        'Agree',
        'Appraise',
        'Prioritize',
        'Support',
        'Prove',
        'Disprove',
        'Assess',
        'Influence',
        'Value',
      ],
    },
  ],
  questionStarters: [
    {
      level: 'Level 1: Recall/Knowledge/Memory',
      starters: [
        'What is it...?',
        'Who is...?',
        'Where is...?',
        'When did...?',
        'Can you list...?',
        'Can you define...?',
        'Which one...?',
        'How much...?',
        'Describe what happened before/after/during...?',
      ],
    },
    {
      level: 'Level 2: Understanding/Comprehension',
      starters: [
        'Can you explain what is meant by...?',
        'Can you explain why...?',
        'Can you write in your own words...?',
        'Can you clarify...?',
        'Who do you think...?',
        'What was the main idea...?',
        'How would you summarize...?',
        'How would you rephrase...?',
        'What can you say about...?',
        'What acts or ideas show...?',
        'What is the main purpose of...?',
      ],
    },
    {
      level: 'Level 3: Application',
      starters: [
        'How would you use...?',
        'Can you calculate the effects of...?',
        'What would result if...?',
        'How would you use/prepare...?',
        'How would you apply... to ...?',
        'What variables would you change to...?',
        'What would result if...?',
        'If ... changed, then what other changes might...?',
        'Do you know another instance where...?',
        'Demonstrate how certain characters are similar or different.',
        'What questions would you ask of...?',
        'Can you illustrate...?',
        'What choice does... (character) face?',
      ],
    },
    {
      level: 'Level 4: Analysis',
      starters: [
        'What is the function of...?',
        'What ideas apply...?',
        'Why do you think...?',
        'Can you compare/contrast...?',
        'What is the relationship between...?',
        'How would you classify...?',
        'Can you list the parts...?',
        'What conclusions can you make...?',
        'Which events could not have happened?',
        'If...happened, what might the ending have been?',
        'How is... similar to...?',
        'Can you distinguish between...?',
        'What was the turning point?',
        'What was the problem with...?',
        'Why did...changes occur?',
      ],
    },
    {
      level: 'Level 5: Synthesis or Create',
      starters: [
        'How would you test...?',
        'Formulate a theory/hypothesis...',
        'How might you organize...?',
        'Predict how... would change if...?',
        'Construct a model that would change...?',
        'What could be combined to improve/change...?',
        'If...is changed, then predict/describe...?',
        'Given..., how would you design...?',
        'What would happen if...?',
        'Can you see a possible solution to...?',
        'Do you agree with the actions?...with the outcomes?',
        'What is your opinion of...?',
        'What do you imagine would have been the outcome if...had made a different choice?',
        'What would you cite to defend the actions of...?',
      ],
    },
    {
      level: 'Level 6: Evaluation',
      starters: [
        'Which is more important...?',
        'How would you rank...?',
        'Do you think...why or why not?',
        'What is the best...?',
        'How would you prioritize...?',
        'What choice would you have made...?',
        'What is the validity of...?',
        'What would you recommend...?',
        'Judge the value of...?',
        'Can you defend the character’s position about...?',
        'Do you think...is a good or bad thing?',
        'Do you believe?',
        'What are the consequences...?',
        'Why did the character choose...?',
        'How can you determine the character’s motivation when...?',
      ],
    },
  ],
};
